

// TOOL:     vlog2tf
// DATE:     Mon Apr 28 19:39:36 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   encoder16to4
// DESIGN:   encoder16to4
// FILENAME: encoder16to4_tf.v
// PROJECT:  decod_estrutural
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module encoder16to4_tf();

// Inputs
    reg [4:0] in;


// Outputs
    wire [15:0] out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    encoder16to4 UUT (
        .in(in), 
        .out(out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            in=3'b001; #5
			in=3'b010; #5
			in=3'b111;
    end

endmodule // encoder16to4_tf