

// TOOL:     vlog2tf
// DATE:     Mon Apr 28 19:57:12 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   mux8x1
// DESIGN:   mux8x1
// FILENAME: mux8x1_tf.v
// PROJECT:  mux_16_1
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module mux8x1_tf();

// Inputs
    reg [2:0] Sel;
    reg [15:0] Dados;


// Outputs
    wire Y;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    mux8x1 UUT (
        .Sel(Sel), 
        .Dados(Dados), 
        .Y(Y)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
	//entrada de dados
        Dados = 4'b0000;
        Dados = 4'b0001;
        Dados = 4'b1111;
        Dados = 4'b1010;
		
// testa todas as combinações de seleção

		Sel = 4'b0000; #10;
		Sel = 4'b0001; #10;
		Sel = 4'b0010; #10;
		Sel = 4'b0011; #10;
		
    end

endmodule // mux8x1_tf