

// TOOL:     vlog2tf
// DATE:     Mon Apr 28 20:24:24 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   mux_n_1
// DESIGN:   mux_n_1
// FILENAME: mux_n_1_tf.v
// PROJECT:  Mux_N_1
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module mux_n_1_tf();

// Inputs
    reg [3:0] in;
    reg [1:0] sel;


// Outputs
    wire out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    mux_n_1 UUT (
        .in(in), 
        .sel(sel), 
        .out(out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            in = 4'b1101;
			sel = 2'b00;
			#5;
			
			in = 4'b1101;
			sel = 2'b01;
			#5;
			
			in = 4'b1101;
			sel = 2'b10;
			#5;
            
			in = 4'b1101;
			sel = 2'b11;
			#5;
    end

endmodule // mux_n_1_tf