

// TOOL:     vlog2tf
// DATE:     Thu May 29 19:51:44 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   pwm
// DESIGN:   pwm
// FILENAME: pwm_tf.v
// PROJECT:  pwm
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module pwm_tf();

// Inputs
    reg clk;
    reg reset;
    reg [3:0] duty;


// Outputs
    wire pwm_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    pwm UUT (
        .clk(clk), 
        .reset(reset), 
        .duty(duty), 
        .pwm_out(pwm_out)
        );

//geração de clock
	initial 
		clk =0;
		always #5 clk =~clk; // periodo de 10ns

// Initialize Inputs
// You can add your stimulus here
    initial begin
            
			//inicialização
			clk =0;
			reset =1;
			duty =0;
			
			#20
			reset =0;
			
            reset = 0;
            duty = 4'b0011; //30%
			#10000
			
			reset = 0;
            duty = 4'b1000; //80%
			#10000
			
			reset = 0;
            duty = 4'b1010; //100%
			#10000
			
			reset = 1;
            duty = 4'b1010; //100%
			#10000
			
			$finish;
			
    end

endmodule // pwm_tf