

// TOOL:     vlog2tf
// DATE:     Tue May 27 20:34:09 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   siso_N
// DESIGN:   siso_N
// FILENAME: siso_N_tf.v
// PROJECT:  SISO_N
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module siso_N_tf();

// Inputs
    reg reset;
    reg clk;
    reg enable;
    reg dir;
    reg data_in;


// Outputs
    wire data_out;
    wire data_out_2;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    siso_N UUT (
        .reset(reset), 
        .clk(clk), 
        .enable(enable), 
        .dir(1'b0), 
        .data_in(data_in), 
        .data_out(data_out)
        );
		
		
	siso_N UUT_2 (
        .reset(reset), 
        .clk(clk), 
        .enable(enable), 
        .dir(1'b1), 
        .data_in(data_in), 
        .data_out(data_out_2)
        );

//geração de clock
	initial 
		clk =0;
		always #5 clk =~clk; // periodo de 10ns
		
		
// Initialize Inputs
// You can add your stimulus here
    initial begin
		
		reset =1;
		enable =0;
		dir =0;
		data_in =0;
		
		#35 reset =0; //libera o reset em 35ns
		#30 enable =1; //habilita em 65ns
		#10 dir =1;   // direção = esquerda em 75ns
		
		//envio de bits : 11001100 (bit a bit em cada 20ns)
		
		#10 data_in =1;    //85 ns
		#20 data_in =1;    //105 ns
		#20 data_in =0;    //125 ns
		#20 data_in =0;    //145 ns
		#20 data_in =1;    //165 ns
		#20 data_in =1;    //185 ns
		#20 data_in =0;    //205 ns
		#20 data_in =0;    //225 ns
		
		//aguarda 20 ns
		
		#20 data_in =0; //245 ns
		
		
		//envio do valor 01010101
		
		data_in =1; #10;
		data_in =0; #10;
		data_in =1; #10;
		data_in =0; #10;
		data_in =1; #10;
		data_in =0; #10;
		data_in =1; #10;
		data_in =0; #10;
		
		#50 $finish;
		
		end
           

endmodule // siso_N_tf